### ISSUE TITLE
ASDF generate warning: Please only define "cl-ppcre" and secondary systems with a name starting with "cl-ppcre/"

### ISSUE THREAD

**Issue by earl-ducaine** [edicl/cl-ppcre#40] opened 2020-01-29 00:19 UTC
Full warning message:

```
WARNING: System definition file #P"/home/me/quicklisp/dists/quicklisp/software/cl-ppcre-20190521-git/cl-ppcre.asd" contains definition for system "cl-ppcre-test". Please only define "cl-ppcre" and secondary systems with a name starting with "cl-ppcre/" (e.g. "cl-ppcre/test") in that file.
```

This is the offending code, in ```cl-ppcre.asd``` (line 72)

```common-lisp
(defsystem :cl-ppcre-test
  :description "Perl-compatible regular expression library tests"
  :author "Dr. Edi Weitz"
  :license "BSD"
  :depends-on (:cl-ppcre :flexi-streams)
  :components ((:module "test"
                        :serial t
                        :components ((:file "packages")
                                     (:file "tests")
                                     (:file "perl-tests")))))

```

**Comment by stassats** [comment] 2020-01-29 20:51
Duplicate of #30

**Closed by stassats** 2020-01-29 20:51 UTC
